apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/khaledsaiidi/flux-helm-wp/manifests
  ref:
    semver: ">=1.0.0"
  layerSelector:
    mediaType: application/vnd.cncf.flux.content.v1.tar+gzip
    operation: extract
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/KhaledSaiidi/flux-helm-wp/.github/workflows/gitops-artifact-pipeline.yml@refs/tags/v[0-9]+\\.[0-9]+\\.[0-9]+$"

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/production
  prune: true
  sourceRef:
    kind: OCIRepository
    name: flux-system
